# Generated by Django 5.2.8 on 2025-11-23 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='design',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cluster_name', models.CharField(max_length=200)),
                ('work_order', models.CharField(max_length=16)),
                ('scope_work', models.CharField(max_length=100)),
                ('subclass', models.CharField(max_length=50)),
                ('project_type', models.CharField(max_length=20)),
                ('year', models.IntegerField()),
                ('RITM', models.CharField(max_length=11)),
                ('region', models.CharField(max_length=20)),
                ('target_area', models.IntegerField()),
                ('date_assigned', models.DateField()),
                ('design_type', models.CharField(max_length=50)),
                ('tools', models.CharField(max_length=50)),
                ('wo_status', models.CharField(max_length=50)),
                ('responsible', models.CharField(max_length=100)),
                ('priority', models.CharField(max_length=20)),
                ('remarks', models.TextField()),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('updated_by', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='survey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cluster_name', models.CharField(max_length=200)),
                ('work_order', models.CharField(max_length=16)),
                ('region', models.CharField(max_length=20)),
                ('project_type', models.CharField(max_length=20)),
                ('RITM', models.CharField(max_length=11)),
                ('target_area', models.IntegerField()),
                ('date_assigned', models.DateField()),
                ('status', models.CharField(max_length=50)),
                ('responsible', models.CharField(max_length=100)),
                ('tools', models.CharField(max_length=50)),
                ('wo_status', models.CharField(max_length=50)),
                ('priority', models.CharField(max_length=20)),
                ('remarks', models.TextField()),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('updated_by', models.CharField(max_length=100)),
            ],
        ),
    ]
