# Generated by Django 5.2.8 on 2025-11-24 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='design',
            name='cluster_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='survey',
            name='cluster_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='survey',
            name='project_type',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='survey',
            name='region',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='survey',
            name='remarks',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='survey',
            name='target_area',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='survey',
            name='updated_by',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
