# Generated by Django 5.2.8 on 2025-11-24 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_alter_design_cluster_name_alter_survey_cluster_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='design',
            name='design_type',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='design',
            name='remarks',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='design',
            name='scope_work',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='design',
            name='target_area',
            field=models.IntegerField(blank=True),
        ),
    ]
