# Generated by Django 5.2.8 on 2025-11-24 12:21

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_alter_survey_updated_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='updated_by',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
