# Generated by Django 5.2.8 on 2025-11-24 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_alter_survey_updated_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='target_area',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
