# Generated by Django 5.2.8 on 2025-12-01 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_alter_design_updated_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='design',
            name='district_name',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
