# Generated by Django 5.2.8 on 2025-12-01 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0011_design_district_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='design',
            name='status',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
