# Generated by Django 5.2.8 on 2025-12-02 11:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0012_design_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='sor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sor_internal_no', models.CharField(blank=True, max_length=4)),
                ('link_codes', models.CharField(blank=True, max_length=300)),
                ('type', models.CharField(max_length=20)),
                ('dwt_sor', models.CharField(blank=True, max_length=10)),
                ('sor_boq_status', models.CharField(max_length=20)),
                ('sor_boq_req_date', models.DateTimeField(blank=True)),
                ('sor_boq_approved_date', models.DateTimeField(blank=True)),
                ('sor_status', models.CharField(max_length=20)),
                ('rfs_boq_status', models.CharField(max_length=20)),
                ('rfs_boq_req_date', models.DateTimeField(blank=True)),
                ('rfs_boq_approved_date', models.DateTimeField(blank=True)),
                ('rfs_status', models.CharField(max_length=20)),
                ('oil_sheet_status', models.CharField(max_length=20)),
                ('oil_req_date', models.DateTimeField(blank=True)),
                ('oil_approved_date', models.DateTimeField(blank=True)),
                ('pac_status', models.CharField(max_length=20)),
                ('pac_req_date', models.DateTimeField(blank=True)),
                ('pac_approved_date', models.DateTimeField(blank=True)),
                ('first_50_invoice_no', models.CharField(max_length=7)),
                ('second_50_invoice_no', models.CharField(max_length=7)),
                ('link_status', models.CharField(max_length=100)),
                ('sor_amount', models.IntegerField()),
                ('dependency', models.CharField(max_length=300)),
                ('remarks', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
