# Generated by Django 5.2.8 on 2025-12-02 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0013_sor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sor',
            old_name='link_codes',
            new_name='link_code',
        ),
        migrations.RemoveField(
            model_name='sor',
            name='link_status',
        ),
        migrations.RemoveField(
            model_name='sor',
            name='type',
        ),
        migrations.AddField(
            model_name='sor',
            name='RITM',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='sor',
            name='contract_no',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='sor',
            name='cost',
            field=models.DecimalField(decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='sor',
            name='overall_sor_total',
            field=models.DecimalField(decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='sor',
            name='sor_overall_status',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='sor',
            name='sor_type',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='sor',
            name='subclass',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='sor',
            name='tools',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='sor',
            name='wo_status',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='sor',
            name='work_order',
            field=models.CharField(blank=True, max_length=16),
        ),
        migrations.AlterField(
            model_name='sor',
            name='first_50_invoice_no',
            field=models.CharField(blank=True, max_length=7),
        ),
        migrations.AlterField(
            model_name='sor',
            name='oil_sheet_status',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='sor',
            name='pac_status',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='sor',
            name='rfs_boq_status',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='sor',
            name='rfs_status',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='sor',
            name='second_50_invoice_no',
            field=models.CharField(blank=True, max_length=7),
        ),
        migrations.AlterField(
            model_name='sor',
            name='sor_amount',
            field=models.DecimalField(decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='sor',
            name='sor_boq_status',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='sor',
            name='sor_status',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
